betterworks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles import views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='chat/', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chat.urls')),
    # Note: If this were for a real deployment, we would want a separate static
    # resources web server to serve these static assets, instead of Django
    url(r'^static/(?P<path>.*)$', views.serve),
]

chat/urls.py
from django.conf.urls import url

from . import auth_views, chat_views, pusher_integration

app_name = 'chat'
urlpatterns = [
    url(r'^$', chat_views.index, name='index'),
    url(r'^find_users/$', chat_views.find_users, name='find_users'),
    url(r'^get_conversations/$', chat_views.get_conversations, name='get_conversations'),
    url(r'^get_messages/$', chat_views.get_messages, name='get_messages'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^post_message/$', chat_views.post_message, name='post_message'),
    url(r'^pusher_auth/', pusher_integration.authenticate, name='pusher_auth'),
]

chat/models.py
"""Database models for the chat application."""

from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Participant(models.Model):
    """A user of the chat application.

    This has a one-to-one association with a User, and may be used to augment
    the User model with properties specific to the chat application, although
    no such augmentations exist yet.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __repr__(self):
        return "Participant(" + str(self.user) + ")"


class Conversation(models.Model):
    """Represents a conversation between two or more participants.

    A conversation may have many participants, and a participant may partake in
    many conversations.
    """
    participants = models.ManyToManyField(Participant)

    def as_dict(self):
        """Converts to dict with info about the latest message.

        Returns:
            dict. Contains two keys. participant_emails lists the emails of each
            participant. last_message contains the dict representation of the
            last message in this conversation.
        """
        return {
            'participant_emails': [
                participant.user.username
                for participant in self.participants.all()
            ],
            'last_message': (
                self.message_set.order_by('-timestamp')[0].as_dict()
            )
        }

    def __repr__(self):
        return "Conversation(" + str(self.participants) + ")"

class Message(models.Model):
    """Represents a message within a conversation.

    A message belongs to exactly one conversation, and was posted by exactly
    one participant. It has text and a time of posting, which is set to be the
    time that it was inserted into the database.
    """
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    participant = models.ForeignKey(Participant)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def as_dict(self):
        """Converts to dict representation.

        Returns:
            dict. Contains the following keys. email contains the email of the
            participant that posted this message. body contains the text of the
            message. timestamp contains the timestamp of the message, formatted
            as a string with format_instant.
        """

        def format_instant(instant):
            """Formats a datetime for display.

            Args:
                instant (datetime): The datetime for display.

            Returns:
                str. The string to display for this timestamp. If the instant's
                year is different than the current year, uses the time and full
                date. Otherwise, if it is a different month or day, uses the
                time and abbreviated month with day. Otherwise, uses the time.
            """
            now = datetime.now()
            if instant.year != now.year:
                return instant.strftime('%-I:%M%P, %b %d, %Y')
            if instant.month != now.month or instant.day != now.day:
                return instant.strftime('%-I:%M%P, %b %d')
            return instant.strftime('%-I:%M%P')

        return {
            'email': self.participant.user.username,
            'body': self.text,
            'timestamp': format_instant(self.timestamp),
        }

    def __repr__(self):
        return (
            "Message("
            + "text=" + self.text + ", "
            + "timestamp=" + str(self.timestamp) + ")"
        )

chat/templates/chat/index.html
{% load staticfiles %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.0/bootstrap3-typeahead.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://js.pusher.com/3.0/pusher.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
<script type="text/javascript">
  CSRF_TOKEN = "{{ csrf_token }}";
  USER_EMAIL = "{{ request.user.username }}";
</script>
<script src="{% static 'js/scripts.js' %}"></script>

<nav class="navbar navbar-default navbar-fixed-top">
  <div id="navbar" class="navbar-header navbar-collapse collapse">
    <form class="navbar-form " id="find_users" method="post">
      {% csrf_token %}
      <input class="form-control" id="email_prefix" name="email_prefix" type="text" placeholder="Search by email" autocomplete="off" />
    </form>
  </div>
  <div class="">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>    	
    <div class="navbar-brand navbar-right" id="page_header">Chats</div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div id="sidebar" class="col-sm-2 col-md-3 sidebar">
      <ul class="nav nav-sidebar">
        <table id="conversations" class="table"></table>
        <li id="logout_button">
          <form action="{% url 'chat:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn btn-default" />
          </form>
        </li>
      </ul>
    </div>
    <div class="col-sm-10 col-sm-offset-2 col-md-9 col-md-offset-3 main">
      <div id="chat_pane" class="collapse">
        <ul id="chat_messages"></ul>
        <form id="post_message" method="post" class="compose-form form-horizontal">
          {% csrf_token %}
          <div class="input-group full-width">
            <input id="message_text" name="message_text" type="text" placeholder="Message" class="form-control" />
            <span class="input-group-btn">
              <input type="submit" value="Send" class="form-control btn btn-primary" />
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

chat/templates/chat/login.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">

<div class="container">
  <form class="form-signin" method="post" action="{% url 'chat:login' %}">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    {% if error %}
      <p>{{ error }}</p>
    {% endif %}
    <label for="email" class="sr-only">Email:</label>
    <input type="email" name="email" class="form-control" placeholder="Email address" required="" autofocus=""></input>
    <label for="password" class="sr-only">Password:</label>
    <input type="password" name="password" class="form-control" placeholder="Password" required=""></input>
    <input type="submit" name="login" value="Log in" class="btn btn-lg btn-primary btn-block"></input>
    <input type="submit" name="sign_up" value="Sign up" class="btn btn-lg btn-block"></input>
    <input type="hidden" name="next" value="{{ next }}" />
  </form>
</div>